import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import PageTransitionEffect from './PageTransitionEffect'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + ' overflow-x-hidden w-screen'}>
        <PageTransitionEffect>{children}</PageTransitionEffect>
      </body>
    </html>
  )
}
